[tool.poetry]
name = "billtitleindex"
version = "0.1.0"
description = ""
authors = ["Ari"]
packages = [{include = "billtitleindex", from = "src", format = "sdist"}]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "3.8.1"
aiosignal = "1.2.0"
amqp = "2.6.1"
anyio = "3.5.0"
asgiref = "3.5.0"
async-timeout = "4.0.2"
asyncpg = "0.25.0"
asynctest = "0.13.0"
attrs = "21.4.0"
beautifulsoup4 = "4.10.0"
billiard = "3.6.4.0"
black = "22.1.0"
cached-property = "1.5.2"
celery = "4.4.6"
certifi = "2021.10.8"
charset-normalizer = "2.0.12"
ciso8601 = "2.2.0"
click = "8.0.3"
click-didyoumean = "0.3.0"
click-plugins = "1.1.1"
click-repl = "0.2.0"
cssselect = "1.1.0"
databases = "0.5.5"
Django = "3.2.12"
django-elasticsearch-dsl = "7.2.2"
elasticsearch = "7.17.0"
elasticsearch-dsl = "7.4.0"
fastapi = "0.74.1"
frozenlist = "1.3.0"
future = "0.18.2"
greenlet = "1.1.2"
gunicorn = "20.1.0"
h11 = "0.13.0"
html5lib = "1.1"
idna = "3.3"
importlib-metadata = "4.11.1"
iso8601 = "1.0.2"
kombu = "4.6.11"
lxml = "4.7.1"
mechanize = "0.4.7"
mock = "4.0.3"
multidict = "6.0.2"
mypy-extensions = "0.4.3"
pathspec = "0.9.0"
platformdirs = "2.5.1"
prompt-toolkit = "3.0.28"
psycopg2-binary = "2.9.3"
pydantic = "1.9.0"
python-dateutil = "2.8.2"
python-decouple = "3.6"
pytz = "2021.3"
PyYAML = "6.0"
requests = "2.27.1"
rtyaml = "1.0.0"
scrapelib = "2.0.6"
six = "1.16.0"
sniffio = "1.2.0"
soupsieve = "2.3.1"
SQLAlchemy = "1.4.31"
sqlparse = "0.4.2"
starlette = "0.17.1"
tomli = "2.0.1"
typed-ast = "1.5.2"
typing-extensions = "4.1.1"
urllib3 = "1.26.8"
uvicorn = "0.17.5"
vine = "1.3.0"
wcwidth = "0.2.5"
webencodings = "0.5.1"
xmltodict = "0.12.0"
yarl = "1.7.2"
zipp = "3.7.0"
united-states-congress = {git="https://github.com/unitedstates/congress", branch="main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''
