:toc: auto

# billtitleindex
Create an index of U.S. bill titles

1. Get and store Bill Status documents from govinfo (e.g. https://www.govinfo.gov/bulkdata/BILLSTATUS/117/hr/BILLSTATUS-117hr4350.xml). The bill status XML examples and developer guide are https://github.com/usgpo/bill-status[here].

Bulk data for recent bills can be downloaded from the ProPublica bulk downloads page https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills[here].

For example, https://s3.amazonaws.com/pp-projects-static/congress/bills/118.zip?_ga=2.133188941.218487348.1644684899-584653619.1643267056[zip file here]

To update this data, it should be possible to `pip install` the `package` branch of the `/unitedstates/congress` repository https://github.com/acxz/congress/tree/python-package[here], and then run `usc-run bills` in the directory that is the parent of the `data` directory.
+
2. Each bill status xml has a `titles` node. This node is a list of bill titles. It has the following form:

```xml
<titles>
<item>
<titleType>Short Titles as Introduced</titleType>
<parentTitleType/>
<title>CLEAR Act of 2011</title>
<chamberCode/>
<chamberName/>
</item>
<item>
<titleType>Short Titles as Introduced</titleType>
<parentTitleType/>
<title>Clear Law Enforcement for Criminal Alien Removal Act of 2011</title>
<chamberCode/>
<chamberName/>
</item>
<item>
<titleType>Official Title as Introduced</titleType>
<parentTitleType/>
<title>To provide for enhanced Federal, State, and local assistance in the enforcement of the immigration laws, to amend the Immigration and Nationality Act, to authorize appropriations to carry out the State Criminal Alien Assistance Program, and for other purposes.</title>
<chamberCode/>
<chamberName/>
</item>
<item>
<titleType>Display Title</titleType>
<parentTitleType/>
<title>CLEAR Act of 2011</title>
<chamberCode/>
<chamberName/>
</item>
</titles>
```

+3. For each bill,(e.g. 117hr4350), use the `lxml` Python library to parse title information into a list of dicts. Each item in the list should have the following keys:
 * title (str, e.g. "CLEAR Act of 2011")
 * titleNoYear (str, e.g. "CLEAR Act")
 * type (str)
 * as (str)
 * is_for_portion (bool)


The parsing should follow the code in the `unitedstates/congress` repository. The goal is to gather only the title metadata, while that repository processes all metadata in the xml. 
 https://github.com/unitedstates/congress/blob/master/tasks/bill_info.py#L55

```python
 titles = make_node(root, "titles", None)
    for title in bill['titles']:
        n = make_node(titles, "title", title['title'])
        n.set("type", title['type'])
        if title['as']:
            n.set("as", title['as'])
        if title['is_for_portion']:
            n.set("partial", "1")
```
+
4. Index the deduplicated titles in Elasticsearch, in a document that also includes the bill number and the list of title dicts above. The index can be searched by bill number and by title.

NOTE: if this can be done cleanly in PostgresSQL with the ability to do full text search, that would be preferred.

+
5. Use the ES index to construct a search query in Python. The query will input a bill number (e.g. 117hr4350) and return a) a list of bills with the same title and b) a list of bills with the same titleNoYear. These lists should include the bill number and the matching title.

For example, if the query is for bill number `117hr4350`, the result should be in the following form:

```javascript
titles: {
"CLEAR Act of 2011": [--list of bills that have this title--],
"Clear Law Enforcement for Criminal Alien Removal Act of 2011": [--list of bills that have this title--],
"To provide for enhanced Federal, State, and local assistance in the enforcement of the immigration laws, to amend the Immigration and Nationality Act, to authorize appropriations to carry out the State Criminal Alien Assistance Program, and for other purposes.": [--list of bills that have this title--]
},
titlesNoYear: {
"CLEAR Act": [--list of bills that have this title--],
"Clear Law Enforcement for Criminal Alien Removal Act": [--list of bills that have this title--],
"To provide for enhanced Federal, State, and local assistance in the enforcement of the immigration laws, to amend the Immigration and Nationality Act, to authorize appropriations to carry out the State Criminal Alien Assistance Program, and for other purposes.": [--list of bills that have this title--]
}
```
+
6. Create an API with FastAPI that accepts a bill number and returns the above result. This should extend the API at https://github.com/aih/billtitles-py. PR requests in that Repo can be used to integrate this functionality.

The API may look like the following:

/bills/titles/116hr2500 ::
list of titles and titlesNoYear, in the form of the above dict

/bills/titles?bills=['117hr21', '116hr2500'...] ::

{
117hr21: { titles: ..., titlesNoYear: ...},
116hr2500: { titles: ..., titlesNoYear: ...}
}

/titles/[title]?fuzzy=True ::
list of matching titles and titlesNoYear, in the form of the above dict


It may also include a POST, to add new titles to the dataset:

POST /bills/titles/116hr4350
```
{
titles: [
"CLEAR Act of 2011",
"Clear Law Enforcement for Criminal Alien Removal Act of 2011",
"To provide for enhanced Federal, State, and local assistance in the enforcement of the immigration laws, to amend the Immigration and Nationality Act, to authorize appropriations to carry out the State Criminal Alien Assistance Program, and for other purposes."
titlesNoYear: [
"CLEAR Act",
"Clear Law Enforcement for Criminal Alien Removal Act",
"To provide for enhanced Federal, State, and local assistance in the enforcement of the immigration laws, to amend the Immigration and Nationality Act, to authorize appropriations to carry out the State Criminal Alien Assistance Program, and for other purposes."
]
```

7. Dockerize the scraping and storage of data, and add to a docker-compose with dockerhub.io/arihersh/billtitles (from https://github.com/aih/billtitles-py)

