@Library('jenkins-shared-lib') _

eksPipeline{
    project = "billtitleindex"
    awsProjectMap = ["739065237548": "dev,stage,prod,preprod"]
    awsClusterMap = ["739065237548": "eks-cluster-main"]
    deployMap = ["dev": "dev", "stage": "stage", "prod": "prod", "preprod": "preprod"]
    artifactName = "billtitleindex"
    promotionMap = ["prod": ["from": "stage"], "preprod": ["from": "stage"]]
}
