# Generated by Django 3.2.12 on 2022-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0004_auto_20220227_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billtitles',
            name='official_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='official title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='popular_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='popular title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='short title'),
        ),
    ]
