# Generated by Django 3.2.12 on 2022-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0005_auto_20220227_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstagetitle',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='billstagetitle',
            name='titleNoYear',
            field=models.CharField(max_length=1000, verbose_name='titleNoYear'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='official_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='official title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='popular_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='popular title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='short_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='short title'),
        ),
    ]
