# Generated by Django 3.2.12 on 2022-02-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0006_auto_20220227_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstagetitle',
            name='bill_basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billstagetitle', to='scrapeindex.billbasic', verbose_name='bill_basic'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='bill_basic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billtitles', to='scrapeindex.billbasic', verbose_name='bill_basic'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='official_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='official_title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='popular_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='popular_title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='short_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='short_title'),
        ),
    ]
