# Generated by Django 3.2.12 on 2022-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0007_auto_20220227_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='billbasic',
            name='bill_number',
            field=models.CharField(default='sres', max_length=20, verbose_name='bill_number'),
            preserve_default=False,
        ),
    ]
