# Generated by Django 3.2.12 on 2022-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0009_alter_billstagetitle_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstagetitle',
            name='As',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='as'),
        ),
    ]
