# Generated by Django 3.2.12 on 2022-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapeindex', '0010_alter_billstagetitle_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billstagetitle',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='billstagetitle',
            name='titleNoYear',
            field=models.CharField(max_length=2000, verbose_name='titleNoYear'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='official_title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='official_title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='popular_title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='popular_title'),
        ),
        migrations.AlterField(
            model_name='billtitles',
            name='short_title',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='short_title'),
        ),
    ]
